# -*- coding: utf-8 -*-
"""Ciencia de Datos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYVDy1O6oLf8ndNz78szs1LSop66Idkh
"""

import numpy as np
from matplotlib import pyplot as plt

data = np.array([
    [10, 146],
    [11, 154],
    [12, 163],
    [13, 174],
    [14, 182],
    [15, 186],
    [16, 191]
])
x, y = data.T
plt.scatter(x,y)
plt.show()